export { default as Waves } from "./Waves";
export { default as MainBox } from "./UserManagementMainDiv";
export { default as ModuleTitle } from "./ModuleTitle";
export { default as BlueButton } from "./BlueButton";
export { default as RedButton } from "./RedButton";
export { default as Card } from "./Card";
export { default as RadioButton } from "./RadioButton";
export { default as InputField } from "./CustomInputField";
export { default as DropDown } from "./DropDown";
export { default as StudentForm } from "./StudentForm";
export { default as TeacherForm } from "./TeacherForm";
export { default as Toast } from "./Toast";
export { default as MainPage } from "./MainPage";
export { default as StudentPage } from "./StudentPage";
export { default as TeacherPage } from "./TeacherPage";
export { default as AddStudentPage } from "./AddStudentPage";
export { default as UpdateStudentPage } from "./UpdateStudentPage";
export { default as DeleteStudentPage } from "./DeleteStudentPage";
export { default as AddTeacherPage } from "./AddTeacherPage";
export { default as UpdateTeacherPage } from "./UpdateTeacherPage";
export { default as DeleteTeacherPage } from "./DeleteTeacherPage";
export { default as HeaderChip } from "./HeaderChip";
export { default as Button } from "./Button";
export { default as Navbar } from "./Navbar";
export { default as LoginHeaderChip } from "./LoginHeaderChip";
export {default as Form} from "./Form";
export {default as Field} from "./DataField";
export {default as AddFeeDiv} from "./AddFee";
